# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Public/Vivado/ECE544_PROJv3/ip_repo/edit_CameraIP_v1_0.cache/wt [current_project]
set_property parent.project_path C:/Users/Public/Vivado/ECE544_PROJv3/ip_repo/edit_CameraIP_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/Users/Public/Vivado/ECE544_PROJv3/ip_repo/CameraIP_1.0
  c:/Users/Public/Vivado/ECE544_PROJv3/ip_repo/CameraIP_1.0
  {c:/Users/Ryan Bornhorst/Desktop/ECE544/ProjectGS/repositories/digilentip-library-master}
  {c:/Users/Ryan Bornhorst/Desktop/ECE544/ProjectGS/repositories/ece544ip-library-master}
} [current_project]
set_property ip_output_repo c:/Users/Public/Vivado/ECE544_PROJv3/ip_repo/edit_CameraIP_v1_0.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Public/Vivado/ECE544_PROJv3/ip_repo/CameraIP_1.0/hdl/CameraIP_v1_0_S00_AXI.v
  C:/Users/Public/Vivado/ECE544_PROJv3/ip_repo/CameraIP_1.0/src/OV7670_capture.v
  C:/Users/Public/Vivado/ECE544_PROJv3/ip_repo/CameraIP_1.0/src/OV7670_controller.v
  C:/Users/Public/Vivado/ECE544_PROJv3/ip_repo/CameraIP_1.0/src/OV7670_wrapper.v
  C:/Users/Public/Vivado/ECE544_PROJv3/ip_repo/CameraIP_1.0/src/i2c_sender.v
  C:/Users/Public/Vivado/ECE544_PROJv3/ip_repo/CameraIP_1.0/src/vga.v
  C:/Users/Public/Vivado/ECE544_PROJv3/ip_repo/CameraIP_1.0/hdl/CameraIP_v1_0.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top CameraIP_v1_0 -part xc7a100tcsg324-1 -directive FewerCarryChains -retiming


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CameraIP_v1_0.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CameraIP_v1_0_utilization_synth.rpt -pb CameraIP_v1_0_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
