# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/n4DDRfpga.xdc

# Block Designs: bd/embsys/embsys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys || ORIG_REF_NAME==embsys} -quiet] -quiet

# IP: bd/embsys/ip/embsys_nexys4IO_0_0/embsys_nexys4IO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_nexys4IO_0_0 || ORIG_REF_NAME==embsys_nexys4IO_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_timer_0_0/embsys_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_axi_timer_0_0 || ORIG_REF_NAME==embsys_axi_timer_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_fit_timer_0_0/embsys_fit_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_fit_timer_0_0 || ORIG_REF_NAME==embsys_fit_timer_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_uartlite_0_0/embsys_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_axi_uartlite_0_0 || ORIG_REF_NAME==embsys_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_microblaze_0_0/embsys_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_0 || ORIG_REF_NAME==embsys_microblaze_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_microblaze_0_axi_periph_0/embsys_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_axi_periph_0 || ORIG_REF_NAME==embsys_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_microblaze_0_axi_intc_0/embsys_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_axi_intc_0 || ORIG_REF_NAME==embsys_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_microblaze_0_xlconcat_0/embsys_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_xlconcat_0 || ORIG_REF_NAME==embsys_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_mdm_1_0/embsys_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_mdm_1_0 || ORIG_REF_NAME==embsys_mdm_1_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_clk_wiz_1_0/embsys_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_clk_wiz_1_0 || ORIG_REF_NAME==embsys_clk_wiz_1_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_rst_clk_wiz_1_100M_0/embsys_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==embsys_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_CameraIP_0_3/embsys_CameraIP_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_CameraIP_0_3 || ORIG_REF_NAME==embsys_CameraIP_0_3} -quiet] -quiet

# IP: bd/embsys/ip/embsys_blk_mem_gen_0_0/embsys_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_blk_mem_gen_0_0 || ORIG_REF_NAME==embsys_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_xbar_0/embsys_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_xbar_0 || ORIG_REF_NAME==embsys_xbar_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_dlmb_v10_0/embsys_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_dlmb_v10_0 || ORIG_REF_NAME==embsys_dlmb_v10_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_ilmb_v10_0/embsys_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_ilmb_v10_0 || ORIG_REF_NAME==embsys_ilmb_v10_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_dlmb_bram_if_cntlr_0/embsys_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==embsys_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_ilmb_bram_if_cntlr_0/embsys_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==embsys_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_lmb_bram_0/embsys_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_lmb_bram_0 || ORIG_REF_NAME==embsys_lmb_bram_0} -quiet] -quiet

# XDC: bd/embsys/embsys_ooc.xdc
